# K3s helm related
get_k3s_url: https://get.k3s.io
get_helm_url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
k3s_version: v1.17.3+k3s1
kube_dashboard_version: v2.0.0-rc5

# Chart urls
helm_chart_url: https://kubernetes-charts.storage.googleapis.com
jetstack_chart_url: https://charts.jetstack.io
personal_chart_url: https://r1cebank.github.io/helm-charts
openvpn_chart_url: http://storage.googleapis.com/kubernetes-charts
traefik_chart: https://containous.github.io/traefik-helm-chart

# Image and image tags
openvpn_image: r1cebank/openvpn
traefik_image: traefik:v2.2
traefik_forward_auth_image: r1cebank/traefik-forward-auth:multiarch
cloudflare_ddns_image: r1cebank/cloudflare-ddns
gitea_image: r1cebank/gitea:v1.11.3
nfs_provisioner_image: quay.io/external_storage/nfs-client-provisioner-arm

# network related
metallb_mode: layer2
ingress_loadbalancer_ip: 192.168.1.120
gitea_ssh_loadbalancer_ip: 192.168.1.121
openvpn_loadbalancer_ip: 192.168.1.122
metallb_address_range: 192.168.1.120-192.168.1.200
traefik_tls_min_version: VersionTLS12
traefik_dashboard_enabled: true
traefik_force_ssl: true

# oauth
oauth_cookie_domain: elica.io
oauth_auth_domain: auth.elica.io
oauth_email_whitelist: siyuangao+okta@gmail.com,siyuangao@gmail.com
sso_provider: oidc #oidc is okta
odic_url: https://okta.elica.io

# file related
temp_dir: /tmp/geck

# storage options
storage:
  storage_type: device
  device: /dev/sda
  location: /mnt/ssd
  wipe: true

# storage:
#   storage_type: local
#   location: /home/k8s/kube_storage
#   wipe: true

# acme
acme_email: siyuangao@gmail.com
acme_staging_url: https://acme-staging-v02.api.letsencrypt.org/directory
acme_prod_url: https://acme-v02.api.letsencrypt.org/directory
# ddns
ddns_domains: "*.elica.io,elica.io"

# which issuer to use for ingress (staging or prod)
cert_issuer: staging
wildcard_cert_domain: "*.elica.io"

# Ingress Information for services here
gitea_ingress_domain: git.elica.io

# External services to be exposed in kubernetes
external_services:
  - name: synology-nas
    ip: 192.168.1.131
    source_port: 5000
    service_port: 80
    protocol: TCP
    ingress_domain: nas.elica.io
  - name: jupyter-lab
    ip: 192.168.1.41
    source_port: 8888
    service_port: 80
    protocol: TCP
    ingress_domain: lab.elica.io

# for ansible
ansible_python_interpreter: "/usr/bin/python"
