apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingress
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ gitea_ingress_domain }}`)
      kind: Rule
      services:
      - name: gitea-gitea-http
        port: 3000
      middlewares:
        - name: kube-system-traefik-sso@kubernetescrd
  tls:
    certResolver: {{ ingress_issuer }}
    domains:
      - main: "{{ wildcard_cert_domain }}"
    options: {}
